MM Blog article
MediaMath/lambda-cron pull request #28
Opened 2017-08-31 12:54 UTC by javibravo

2017-09-25 13:09 UTC, sean-garvey submitted a review, later dismissed

2017-09-25 13:10 UTC, sean-garvey commented on article.md
> +It was how LambdaCron was worn.
*born

2017-09-25 13:40 UTC, javibravo commented
@sean-garvey, @nickagel, @vincetse, 

Open to hear suggestions to improve the article: things to include or remove.
Don't be shy to correct me if there are better ways to say something, I bet there many things can be improved.

2017-10-16 08:03 UTC, javibravo commented
@fsargent ,
I am about to open source LambdaCron. I have been working in an article for MM blog. I would like you to review it and suggest any change/update if required.

2017-10-25 08:20 UTC, javibravo commented
@fsargent , I have added some small changes: https://github.com/MediaMath/lambda-cron/pull/28/commits/ac250ad23fc952d6b83530ea59abf7b7629d7029

@fsargent , @vincetse , 
I would like a final review (and approval if proceed) from you. After that I will merge and publish.
Thanks.

2017-10-25 15:39 UTC, fsargent requested changes

2017-10-25 15:39 UTC, fsargent commented on article.md
> +LambdaCron CLI also provides commands that can automate development and maintenace tasks. E.G. validate and upload tasks to a LambdaCron environment using  Continuous Integration tools. We will follo
maintenance*

2017-10-25 15:39 UTC, fsargent commented on article.md
> +AWS configures events using [CloudWatch](http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/WhatIsCloudWatchEvents.html), to invoke other AWS services in a cron-like way. As the team's infrast
This is a negative change. 
You don't need ",service which is" 
Preakness should have two 's' to be consistent with the rest of the article.

Revert this change.

2017-10-25 18:11 UTC, javibravo commented
@fsargent , fixed.

2017-10-25 20:54 UTC, fsargent approved these changes

2017-10-25 21:24 UTC, sean-garvey approved these changes

2017-10-26 07:21 UTC, merged